# 酸奶成本9元， 酸奶利润1元
# 预测多了损失大，故不要预测多，故生成的模型会少预测一些

In [1]:

#0导入模块，生成数据集
import tensorflow as tf
import numpy as np
BATCH_SIZE = 8
SEED = 23455
COST = 9
PROFIT = 1

rdm = np.random.RandomState(SEED)
X = rdm.rand(32,2)
Y = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

#1定义神经网络的输入、参数和输出，定义前向传播过程。
x = tf.placeholder(tf.float32, shape=(None, 2))
y_ = tf.placeholder(tf.float32, shape=(None, 1))
w1= tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

#2定义损失函数及反向传播方法。
#重新定义损失函数，使得预测多了的损失大，于是模型应该偏向少的方向预测。
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_)*COST, (y_ - y)*PROFIT))
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

#3生成会话，训练STEPS轮。
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 3000
    for i in range(STEPS):
        start = (i*BATCH_SIZE) % 32
        end = (i*BATCH_SIZE) % 32 + BATCH_SIZE
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 500 == 0:
            print ("After %d training steps, w1 is: " % (i))
            print (sess.run(w1), "\n")
    print ("Final w1 is: \n", sess.run(w1))


After 0 training steps, w1 is: 
[[-0.80594873]
 [ 1.48737288]] 

After 500 training steps, w1 is: 
[[ 0.8732146 ]
 [ 1.00620401]] 

After 1000 training steps, w1 is: 
[[ 0.96580642]
 [ 0.9698208 ]] 

After 1500 training steps, w1 is: 
[[ 0.96454471]
 [ 0.96829462]] 

After 2000 training steps, w1 is: 
[[ 0.96024752]
 [ 0.97420841]] 

After 2500 training steps, w1 is: 
[[ 0.96100295]
 [ 0.96993417]] 

Final w1 is: 
 [[ 0.96004069]
 [ 0.97334176]]
