In [1]:
#coding:utf-8
#预测多或预测少的影响一样
#0导入模块，生成数据集
import tensorflow as tf
import numpy as np
BATCH_SIZE = 8
SEED = 23455

rdm = np.random.RandomState(SEED)
X = rdm.rand(32,2)
Y_ = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

#1定义神经网络的输入、参数和输出，定义前向传播过程。
x = tf.placeholder(tf.float32, shape=(None, 2))
y_ = tf.placeholder(tf.float32, shape=(None, 1))
w1= tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

#2定义损失函数及反向传播方法。
#定义损失函数为MSE,反向传播方法为梯度下降。
loss_mse = tf.reduce_mean(tf.square(y_ - y))
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss_mse)

#3生成会话，训练STEPS轮
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 20000
    for i in range(STEPS):
        start = (i*BATCH_SIZE) % 32
        end = (i*BATCH_SIZE) % 32 + BATCH_SIZE
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y_[start:end]})
        if i % 500 == 0:
            print ("After %d training steps, w1 is: " % (i))
            print (sess.run(w1), "\n")
    print ("Final w1 is: \n", sess.run(w1))
#在本代码#2中尝试其他反向传播方法，看对收敛速度的影响，把体会写到笔记中

After 0 training steps, w1 is: 
[[-0.80974597]
 [ 1.48529029]] 

After 500 training steps, w1 is: 
[[-0.46074435]
 [ 1.64187801]] 

After 1000 training steps, w1 is: 
[[-0.21939856]
 [ 1.69847655]] 

After 1500 training steps, w1 is: 
[[-0.04415595]
 [ 1.70031762]] 

After 2000 training steps, w1 is: 
[[ 0.08942621]
 [ 1.67332804]] 

After 2500 training steps, w1 is: 
[[ 0.19583555]
 [ 1.63226771]] 

After 3000 training steps, w1 is: 
[[ 0.28375748]
 [ 1.58544338]] 

After 3500 training steps, w1 is: 
[[ 0.35848638]
 [ 1.53744721]] 

After 4000 training steps, w1 is: 
[[ 0.42332518]
 [ 1.49073935]] 

After 4500 training steps, w1 is: 
[[ 0.48040026]
 [ 1.4465574 ]] 

After 5000 training steps, w1 is: 
[[ 0.53113604]
 [ 1.40545356]] 

After 5500 training steps, w1 is: 
[[ 0.57653248]
 [ 1.36759412]] 

After 6000 training steps, w1 is: 
[[ 0.61732584]
 [ 1.33294034]] 

After 6500 training steps, w1 is: 
[[ 0.65408462]
 [ 1.30134261]] 

After 7000 training steps, w1 is: 
[[ 0.6872685 ]
 [