In [2]:
%matplotlib inline

What is PyTorch? 什么是PyTorch?
================

基于Python的科学计算包，针对两种用户：
-  用GPUs的力量代替NumPy
-  提供最大灵活性和速度的深度学习研究平台

入门指南
---------------

Tensors 张量

张量和NumPy的ndarray相似，此外，张量还可以用于GPU加速计算。

In [3]:
from __future__ import print_function
import torch

## 构造一个未初始化的5x3矩阵：

In [7]:
x = torch.empty(5, 3)
print(x)

tensor(1.00000e-04 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [-1.6487,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [-1.6695,  0.0000,  0.0000]])


## 构造一个随机初始化的矩阵：

In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.4302,  0.4882,  0.7479],
        [ 0.6593,  0.5342,  0.4782],
        [ 0.9553,  0.8458,  0.8879],
        [ 0.5151,  0.2633,  0.6240],
        [ 0.8034,  0.4611,  0.9360]])


## 构建一个充满0（dtype long 类型）的矩阵：

In [9]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


## 直接从数据中构造一个张量：

In [16]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


## 在现有张量的基础上建立一个张量。
这些方法将重用输入张量的属性，如dtype，除非用户提供新的值。

In [17]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 1.4728, -0.0207,  0.7442],
        [-1.1181, -0.0440, -0.1143],
        [-0.4801, -0.8028, -1.4296],
        [ 0.7651,  1.1484,  1.3892],
        [ 0.9392,  1.0534, -1.2495]])


## 得到它的大小:

In [18]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

``torch.Size``实际上是一个元组，所以它支持所有的tuple操作。

Operations 操作

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

操作有多个语法。在下面的例子中，我们看一看加法操作的几种语法。

Addition: syntax 1

加法：语法1

In [19]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.1478,  0.2318,  0.9769],
        [-0.6547,  0.9241,  0.6656],
        [-0.4033, -0.2479, -0.6643],
        [ 1.0087,  1.6271,  1.4563],
        [ 0.9689,  2.0410, -0.2961]])


Addition: syntax 2

加法：语法2 

In [20]:
print(torch.add(x, y))

tensor([[ 2.1478,  0.2318,  0.9769],
        [-0.6547,  0.9241,  0.6656],
        [-0.4033, -0.2479, -0.6643],
        [ 1.0087,  1.6271,  1.4563],
        [ 0.9689,  2.0410, -0.2961]])


Addition: providing an output tensor as argument

加法：作为参数提供一个输出张量

In [21]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.1478,  0.2318,  0.9769],
        [-0.6547,  0.9241,  0.6656],
        [-0.4033, -0.2479, -0.6643],
        [ 1.0087,  1.6271,  1.4563],
        [ 0.9689,  2.0410, -0.2961]])


Addition: in-place

加法：in-place

In [22]:
# adds x to y
y.add_(x)
print(x)
print(y)

tensor([[ 1.4728, -0.0207,  0.7442],
        [-1.1181, -0.0440, -0.1143],
        [-0.4801, -0.8028, -1.4296],
        [ 0.7651,  1.1484,  1.3892],
        [ 0.9392,  1.0534, -1.2495]])
tensor([[ 2.1478,  0.2318,  0.9769],
        [-0.6547,  0.9241,  0.6656],
        [-0.4033, -0.2479, -0.6643],
        [ 1.0087,  1.6271,  1.4563],
        [ 0.9689,  2.0410, -0.2961]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

## 任何对一个张量进行改变的操作都是用"\_"做后缀。

例如： ``x.copy_(y)``, ``x.t_()``,将会改变 ``x``.

You can use standard NumPy-like indexing with all bells and whistles!

您可以使用标准的“NumPy-like索引”这样诱人的功能！

In [26]:
print(x[:, 1])# X[:,0]就是取所有行的第0个数据, X[:,1] 就是取所有行的第1个数据。

tensor([ 0.8756,  1.2712,  0.0150,  1.7948])


## 调整大小：如果你想要调整/重塑张量，你可以使用“torch.view”：

In [25]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x)
print(y)
print(z)
print(x.size(), y.size(), z.size())

tensor([[-0.4417,  0.8756, -0.9419,  0.8557],
        [ 1.0191,  1.2712,  0.9177,  0.4022],
        [-0.0385,  0.0150, -0.4862, -0.2996],
        [ 1.5960,  1.7948, -1.0182,  1.4542]])
tensor([-0.4417,  0.8756, -0.9419,  0.8557,  1.0191,  1.2712,  0.9177,
         0.4022, -0.0385,  0.0150, -0.4862, -0.2996,  1.5960,  1.7948,
        -1.0182,  1.4542])
tensor([[-0.4417,  0.8756, -0.9419,  0.8557,  1.0191,  1.2712,  0.9177,
          0.4022],
        [-0.0385,  0.0150, -0.4862, -0.2996,  1.5960,  1.7948, -1.0182,
          1.4542]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## 如果你有一个元素张量，使用'.item（）'来取值作为Python的值

In [23]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1962])
-1.1962311267852783


**Read later:**
稍后阅读

100多个张量运算，包括转置，索引，切片，数学运算，线性代数，随机数等等，在这里描述< http://pytorch.org/docs/torch > _。

NumPy Bridge
------------

将一个Torch张量转换成一个NumPy阵列，反之亦然。

Torch张量和NumPy阵列将共享它们的底层内存位置，改变一个则另一个会随之改变。

将一个Torch张量转换成一个NumPy阵列

In [28]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


看看numpy数组是如何在值中改变的。

In [30]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

将NumPy数组转换成Torch张量

See how changing the np array changed the Torch Tensor automatically

看看如何把np阵列自动变成了Torch张量

In [44]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

CPU上所有的张量（除了CharTensor）支持转换为NumPy和转回。

CUDA Tensors CUDA张量
------------

Tensors can be moved onto any device using the ``.to`` method.

使用``.to``方法可以把张量移动到任何设备上。

In [43]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([ 2.0499], device='cuda:0')
tensor([ 2.0499], dtype=torch.float64)


In [45]:
z

tensor([ 2.0499], device='cuda:0')

In [46]:
z.to("cpu", torch.double)

tensor([ 2.0499], dtype=torch.float64)

In [47]:
z.to("cpu", torch.float)

tensor([ 2.0499])

In [48]:
z.to("cpu", torch.float64)

tensor([ 2.0499], dtype=torch.float64)