In [1]:
%matplotlib inline


Tensors
=======

Tensors behave almost exactly the same way in PyTorch as they do in Torch.

张量在PyTorch上的表现与在Torch上几乎是一样的。

Create a tensor of size (5 x 7) with uninitialized memory:


用未初始化的内存创建一个大小（5 x 7）的张量：

In [25]:
import torch
a = torch.empty(5, 7, dtype=torch.float)

In [26]:
a

tensor([[ 5.3266e-39,  7.3470e-39,  1.0194e-38,  1.0469e-38,  1.0010e-38,
          6.4285e-39,  9.9184e-39],
        [ 1.0561e-38,  7.1633e-39,  6.7041e-39,  6.7041e-39,  2.9388e-39,
          1.0194e-38,  1.0286e-38],
        [ 1.0469e-38,  1.0653e-38,  1.0194e-38,  8.4490e-39,  1.0837e-38,
          1.0194e-38,  9.9184e-39],
        [ 6.3368e-39,  1.0653e-38,  9.0000e-39,  1.0102e-38,  1.1020e-38,
          4.7755e-39,  9.9184e-39],
        [ 9.0000e-39,  1.0010e-38,  9.9184e-39,  1.0194e-38,  4.2246e-39,
          9.9184e-39,  1.5134e-43]])

Initialize a double tensor randomized with a normal distribution with mean=0,var=1:

初始化一个具有正态分布的double类型张量，均值=0，var=1：

In [3]:
a = torch.randn(5, 7, dtype=torch.double)
print(a)
print(a.size())

tensor([[-1.2750, -1.0954, -0.3850, -0.4567,  0.1513,  1.2243,  0.2648],
        [ 0.1127, -1.7398, -1.3294,  0.3334,  1.0473,  0.8184, -1.5414],
        [-0.9335, -0.5500, -1.3084, -1.7224, -0.4345,  0.4474,  0.3734],
        [-1.7688,  0.3545, -0.0823,  1.5180,  0.1939,  1.0314,  0.8944],
        [ 0.5676, -0.5146,  2.1145,  1.5334, -1.4174,  0.3882, -1.9060]], dtype=torch.float64)
torch.Size([5, 7])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>
``torch.Size``实际上是一个元组，所以它支持相同的操作
Inplace / Out-of-place
----------------------

The first difference is that ALL operations on the tensor that operate in-place on it will have an ``_`` postfix. 

第一个区别是，在它上面的张量上的所有操作都有一个“后缀”。

For example, ``add`` is the out-of-place version, and ``add_`` is the in-place version.

例如，add是 out-of-place版本，add_ 是in-place版本

In [28]:
a.fill_(3.5)
# a has now been filled with the value 3.5

b = a.add(4.0)
# a is still filled with 3.5
# new tensor b is returned with values 3.5 + 4.0 = 7.5

In [29]:
a

tensor([[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000]])

In [30]:
b

tensor([[ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000]])

Some operations like ``narrow`` do not have in-place versions, and hence, ``.narrow_`` does not exist.

一些像``narrow``这样的操作没有in-place版本，因此，``.narrow_``并不存在。

Similarly, some operations like ``fill_`` do not have an out-of-place version, so ``.fill`` does not exist.

类似地，``fill_``之类的操作没有一个out-of-place版本，所以``.fill``不存在。

Zero Indexing 零索引
-------------

Another difference is that Tensors are zero-indexed. (In lua, tensors are one-indexed)

另一个区别是，张量是零索引的。（在lua中，张量是一个索引的）

In [31]:
b = a[0, 3]  # select 1st row, 4th column from a

In [34]:
b

tensor(3.5000)

Tensors can be also indexed with Python's slicing

张量也可以用Python的切片进行索引

In [14]:
b = a[:, 3:5]  # selects all rows, 4th column and  5th column from a

In [15]:
b

tensor([[ 3.5000,  3.5000],
        [ 3.5000,  3.5000],
        [ 3.5000,  3.5000],
        [ 3.5000,  3.5000],
        [ 3.5000,  3.5000]], dtype=torch.float64)

No camel casing 不再使用驼峰命名法
---------------

The next small difference is that all functions are now NOT camelCase anymore. 

下一个小的区别是，所有的函数现在都不再是camelCase了。(camelCase叫做“骆驼式命名法”，是指在英语中，依靠单词的大小写拼写复合词的做法。)

For example ``indexAdd`` is now called ``index_add_``

例如``indexAdd`` 现在写作 ``index_add_``

In [37]:
x = torch.ones(5, 5)
print(x)

tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])


In [38]:
z = torch.empty(5, 2)
z[:, 0] = 10
z[:, 1] = 100
print(z)

tensor([[  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.]])


In [39]:
x.index_add_(1, torch.tensor([4, 0], dtype=torch.long), z)# z 的 第二列 与 x 的 第一列 相加， z的 第一列 与 x 的第五列 相加
print(x)

tensor([[ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.]])


In [42]:
x.index_add_(1, torch.tensor([2, 3], dtype=torch.long), z)
print(x)

tensor([[ 201.,    1.,   11.,  101.,   21.],
        [ 201.,    1.,   11.,  101.,   21.],
        [ 201.,    1.,   11.,  101.,   21.],
        [ 201.,    1.,   11.,  101.,   21.],
        [ 201.,    1.,   11.,  101.,   21.]])


Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

将一个torch张量转换成一个numpy阵列，反之亦然。

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

torch张量和numpy阵列将共享它们的底层内存位置，而改变一个则会改变另一个。

Converting torch Tensor to numpy Array

将torch张量转换为numpy阵列

In [49]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [50]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [51]:
a.add_(1)
print(a)
print(b)  # see how the numpy array changed in value

tensor([ 2.,  2.,  2.,  2.,  2.])
[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor

将numpy数组转换成火炬张量

In [52]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # see how changing the np array changed the torch Tensor automatically

[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

CPU上所有的张量（除了CharTensor）支持转换为NumPy和转回。

CUDA Tensors
------------

CUDA Tensors are nice and easy in pytorch, and transfering a CUDA tensor from the CPU to GPU will retain its underlying type.

CUDA张量在pytorch中很好也很容易，将一个CUDA张量从CPU转移到GPU上，将保留它的底层类型。

In [23]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():

    # creates a LongTensor and transfers it to GPU as torch.cuda.LongTensor
    a = torch.full((10,), 3, device=torch.device("cuda"))
    print(type(a))
    b = a.to(torch.device("cpu"))
    # transfers it to CPU, back to being a torch.LongTensor

<class 'torch.Tensor'>


In [24]:
b

tensor([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])