http://www.pytorchtutorial.com/pytorch-backward/

https://github.com/L1aoXingyu/pytorch-beginner/tree/master/11-backward

In [1]:
import torch 

In [2]:
a = torch.FloatTensor([2, 4, 6])
a.requires_grad = True
a.mean()

tensor(4.)

In [3]:
out = a.mean()
out.backward()
out

tensor(4.)

In [4]:
out.item()

4.0

In [5]:
a.grad.data

tensor([ 0.3333,  0.3333,  0.3333])

In [6]:
# simple gradient
print('=====simple gradient======')
a = torch.FloatTensor([2, 3])
a.requires_grad = True
b = a + 3
c = b * b * 3
print('a :',a.data)
print('b :',b.data)
print('c :',c.data)
out = c.mean()
print('out:',out)
out.backward()
print('计算结果 :')
print(out.item())
print('梯度 :')
print(a.grad.data)

=====simple gradient======
a : tensor([ 2.,  3.])
b : tensor([ 5.,  6.])
c : tensor([  75.,  108.])
out: tensor(91.5000)
计算结果 :
91.5
梯度 :
tensor([ 15.,  18.])


In [13]:
# backward on non-scalar output
m = torch.FloatTensor([[2, 3]])
m.requires_grad = True
print(m)
n = torch.zeros(1, 2)
print(n)
print('*'*10)
n[0, 0] = m[0, 0] ** 2
n[0, 1] = m[0, 1] ** 3
print(m)
print(n)
n.backward(torch.FloatTensor([[1, 1]]))
print('*'*10)
print('=====non scalar output======')
print('input')
print(m.data)
print('input gradients are')
print(m.grad.data)

tensor([[ 2.,  3.]])
tensor([[ 0.,  0.]])
**********
tensor([[ 2.,  3.]])
tensor([[  4.,  27.]])
**********
=====non scalar output======
input
tensor([[ 2.,  3.]])
input gradients are
tensor([[  4.,  27.]])


In [15]:
# jacobian
j = torch.zeros(2 ,2)
k = torch.zeros(1, 2)
m.grad.data.zero_()
k[0, 0] = m[0, 0] ** 2 + 3 * m[0 ,1]
k[0, 1] = m[0, 1] ** 2 + 2 * m[0, 0]
k.backward(torch.FloatTensor([[1, 0]]), retain_graph=True)
j[:, 0] = m.grad.data
m.grad.data.zero_()
k.backward(torch.FloatTensor([[0, 1]]))
j[:, 1] = m.grad.data
print('jacobian matrix is')
print(j)

jacobian matrix is
tensor([[ 4.,  2.],
        [ 3.,  6.]])


In [21]:
# compute jacobian matrix
x = torch.FloatTensor([2, 1]).view(1, 2)
x.requires_grad=True
y = torch.FloatTensor([[1, 2], [3, 4]])

z = torch.mm(x, y)
jacobian = torch.zeros((2, 2))
z.backward(torch.FloatTensor([[1, 0]]), retain_graph=True)  # dz1/dx1, dz1/dx2
jacobian[:, 0] = x.grad.data
x.grad.data.zero_()
z.backward(torch.FloatTensor([[0, 1]]))  # dz2/dx1, dz2/dx2
jacobian[:, 1] = x.grad.data
print('=========jacobian========')
print('x:')
print(x.data)
print('y:')
print(y.data)
print('compute result:')
print(z.data)
print('jacobian matrix is:')
print(jacobian)

=========jacobian========
x:
tensor([[ 2.,  1.]])
y:
tensor([[ 1.,  2.],
        [ 3.,  4.]])
compute result:
tensor([[ 5.,  8.]])
jacobian matrix is:
tensor([[ 1.,  2.],
        [ 3.,  4.]])
