Ref：https://www.jianshu.com/p/a380222a3292

基于NumPy的算法要比纯Python快10到100倍（甚至更快），并且使用的内存更少。

In [5]:
import numpy as np
import time

In [6]:
my_arr = np.arange(1000000)

In [7]:
my_list = list(range(1000000))

- why have not CPU TIME like book ? because different between Linux and Windows?

In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2 

Wall time: 32.1 ms


In [9]:
% time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.11 s


In [10]:
time.clock()

1.4629711091323268

In [11]:
time.time()

1520260724.4772754

In [12]:
start_CPU = time.clock()
for _ in range(10): my_arr2 = my_arr * 2
end_CPU = time.clock()
print("Method 1: %f CPU seconds" % (end_CPU - start_CPU))

Method 1: 0.031829 CPU seconds


In [13]:
start_CPU = time.clock()
for _ in range(10): my_list2 = [x * 2 for x in my_list]
end_CPU = time.clock()
print("Method 2: %f CPU seconds" % (end_CPU - start_CPU))

Method 2: 1.131245 CPU seconds


#  ndarray：一种多维数组对象

In [14]:
# Generate some random data
data = np.random.randn(2, 3)

print(data)
print(data * 10)
print(data + data)



[[ 0.26034514 -0.29806535 -1.46475601]
 [ 0.1968852  -0.41016317  0.43379819]]
[[  2.60345135  -2.98065355 -14.6475601 ]
 [  1.96885197  -4.1016317    4.33798188]]
[[ 0.52069027 -0.59613071 -2.92951202]
 [ 0.39377039 -0.82032634  0.86759638]]


- shape（一个表示各维度大小的元组）
- dtype（一个用于说明数组数据类型的对象）

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

## Create ndarray

In [17]:
data1 = [6, 7.5, 8, 0, 1]

In [18]:
arr1 = np.array(data1)

In [19]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [20]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [21]:
arr2 = np.array(data2)

In [22]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.ndim

2

In [24]:
arr2.shape

(2, 4)

In [25]:
arr2.dtype

dtype('int32')

In [26]:
arr1.dtype

dtype('float64')

zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可：

In [27]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [28]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [29]:
np.empty((2,3,2))

array([[[  1.06411013e-311,   3.16202013e-322],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   1.11640815e-046]],

       [[  5.53517715e+174,   9.06884523e-043],
        [  1.17740318e-047,   1.32764350e-075],
        [  1.09755460e-071,   1.84644673e-076]]])

In [30]:
np.ones((2,2,2))

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

In [31]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## ndarray的数据类型 2018.3.5 1:02

In [32]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [33]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [34]:
arr1.dtype

dtype('float64')

In [35]:
arr2.dtype

dtype('int32')

In [38]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [39]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [40]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [41]:
arr = np.arange(10)

In [42]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[5]

5

In [44]:
arr[5:8]

array([5, 6, 7])

In [45]:
arr[5:8] = 12

In [46]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [48]:
data

array([[ 1.47166184, -1.071032  , -1.1748469 , -1.65725399],
       [-0.31419542, -0.7923428 ,  2.31122921,  1.73305051],
       [ 1.12070629,  0.4326788 , -0.20647059,  0.8930799 ],
       [ 0.54927465, -0.77211894, -0.33192546,  0.81119811],
       [ 0.16005305,  0.79527813, -0.0685844 , -0.66559155],
       [ 0.77588807,  0.19988224,  0.16988174,  0.10411377],
       [ 2.00652218,  0.67135125,  0.1927357 , -1.844389  ]])

Boolean Indexing 

In [50]:
data[names == 'Bob']

array([[ 1.47166184, -1.071032  , -1.1748469 , -1.65725399],
       [ 0.54927465, -0.77211894, -0.33192546,  0.81119811]])