Ref：https://www.jianshu.com/p/a380222a3292

基于NumPy的算法要比纯Python快10到100倍（甚至更快），并且使用的内存更少。

In [1]:
import numpy as np
import time

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

- why have not CPU TIME like book ? because different between Linux and Windows?

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2 

Wall time: 25 ms


In [5]:
% time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.1 s


In [6]:
time.clock()

1.157043194369303

In [7]:
time.time()

1520336532.6997077

In [8]:
start_CPU = time.clock()
for _ in range(10): my_arr2 = my_arr * 2
end_CPU = time.clock()
print("Method 1: %f CPU seconds" % (end_CPU - start_CPU))

Method 1: 0.023743 CPU seconds


In [9]:
start_CPU = time.clock()
for _ in range(10): my_list2 = [x * 2 for x in my_list]
end_CPU = time.clock()
print("Method 2: %f CPU seconds" % (end_CPU - start_CPU))

Method 2: 1.099194 CPU seconds


#  ndarray：一种多维数组对象

In [10]:
# Generate some random data
data = np.random.randn(2, 3)

print(data)
print(data * 10)
print(data + data)



[[ 0.18617022 -0.69417908  1.08285914]
 [-0.29753777  1.15807477 -1.02521642]]
[[  1.86170225  -6.94179083  10.82859137]
 [ -2.97537769  11.58074767 -10.25216418]]
[[ 0.37234045 -1.38835817  2.16571827]
 [-0.59507554  2.31614953 -2.05043284]]


- shape（一个表示各维度大小的元组）
- dtype（一个用于说明数组数据类型的对象）

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

## Create ndarray

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr2.dtype

dtype('int32')

In [22]:
arr1.dtype

dtype('float64')

zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可：

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2,3,2))

array([[[9.91670901e-312, 2.42092166e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.16095484e-028]],

       [[7.52736939e+252, 5.22996085e-067],
        [6.32672818e+180, 4.74483502e+170],
        [1.90299681e-052, 4.93432906e+257]]])

In [26]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## ndarray的数据类型 2018.3.5 1:02

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [29]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

In [32]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [33]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [34]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
arr = np.arange(10)

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [38]:
arr[5:8]

array([5, 6, 7])

In [39]:
arr[5:8] = 12

In [40]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [42]:
data

array([[-0.20435083, -0.16320703, -0.64157279, -0.20765228],
       [ 1.13933598, -1.27446409, -0.64405049,  1.13763244],
       [ 0.09792872,  0.3867323 ,  1.18405646, -0.43031219],
       [ 0.80598   , -0.91108637, -1.24378775, -0.69173487],
       [-0.05054073,  0.90100805, -0.4458398 , -0.45290096],
       [ 0.28340701, -0.50643929, -0.28746125, -0.81338185],
       [-1.45998843, -0.81713014, -1.37090319,  0.41054566]])

Boolean Indexing 

In [43]:
data[names == 'Bob']

array([[-0.20435083, -0.16320703, -0.64157279, -0.20765228],
       [ 0.80598   , -0.91108637, -1.24378775, -0.69173487]])

In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [45]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [46]:
data = np.random.randn(7, 4)

In [47]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [48]:
data

array([[ 0.54319504, -1.7145629 ,  0.59817993, -1.82188945],
       [-0.91960638,  0.46020963,  0.52339049,  0.60364951],
       [ 1.26086643,  0.81415677,  0.41214965,  0.23132608],
       [ 0.37853492,  0.23397204,  1.73654577, -1.54088577],
       [-0.08514287,  0.96284372,  1.47116925, -0.55575983],
       [-0.64511534,  0.31759092,  0.22555252, -0.31685077],
       [ 0.9928156 ,  0.52224085,  0.09978133, -0.80785791]])

In [49]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [50]:
data[names == 'Bob']

array([[ 0.54319504, -1.7145629 ,  0.59817993, -1.82188945],
       [ 0.37853492,  0.23397204,  1.73654577, -1.54088577]])

In [51]:
data[names == 'Bob', 2:]

array([[ 0.59817993, -1.82188945],
       [ 1.73654577, -1.54088577]])

In [52]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [53]:
data[~(names == 'Bob')]

array([[-0.91960638,  0.46020963,  0.52339049,  0.60364951],
       [ 1.26086643,  0.81415677,  0.41214965,  0.23132608],
       [-0.08514287,  0.96284372,  1.47116925, -0.55575983],
       [-0.64511534,  0.31759092,  0.22555252, -0.31685077],
       [ 0.9928156 ,  0.52224085,  0.09978133, -0.80785791]])

In [54]:
mask = (names == 'Bob') | (names == 'Will')

In [55]:
data[mask]

array([[ 0.54319504, -1.7145629 ,  0.59817993, -1.82188945],
       [ 1.26086643,  0.81415677,  0.41214965,  0.23132608],
       [ 0.37853492,  0.23397204,  1.73654577, -1.54088577],
       [-0.08514287,  0.96284372,  1.47116925, -0.55575983]])

In [56]:
data[data < 0] = 0
data

array([[0.54319504, 0.        , 0.59817993, 0.        ],
       [0.        , 0.46020963, 0.52339049, 0.60364951],
       [1.26086643, 0.81415677, 0.41214965, 0.23132608],
       [0.37853492, 0.23397204, 1.73654577, 0.        ],
       [0.        , 0.96284372, 1.47116925, 0.        ],
       [0.        , 0.31759092, 0.22555252, 0.        ],
       [0.9928156 , 0.52224085, 0.09978133, 0.        ]])

In [57]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.46020963, 0.52339049, 0.60364951],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.31759092, 0.22555252, 0.        ],
       [0.9928156 , 0.52224085, 0.09978133, 0.        ]])

# Fancy Indexing
edit by david ,2018.3.6,C1-211 12:50

In [58]:
arr = np.empty((8, 4))

In [59]:
for i in range(8):
    arr[i] = i

In [60]:
for i in range(8):
    arr[i] = i

In [61]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])