In [2]:
import numpy as np
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

开方

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

自然对数

In [5]:
np.exp(arr) #自然常数e为底的指数函数

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [6]:
x = np.random.randn(8)
y = np.random.randn(8)    

In [7]:
x

array([ 0.67889009,  0.43168421,  0.73073508, -0.98056619,  0.17613045,
        0.45484935,  1.71123488, -1.90252539])

In [8]:
y

array([ 0.43870343,  1.13496456, -0.3878158 , -0.83633501, -0.43907358,
       -0.09951792, -1.10734006, -0.47218999])

求最大值

In [10]:
np.maximum(x, y)

array([ 0.67889009,  0.43168421,  0.73073508, -0.42797124,  1.36742574,
        0.45484935,  1.71123488, -1.80004884])

In [13]:
arr = np.random.randn(7) * 5 #从标准正态分布中返回一个或多个样本值

In [14]:
arr

array([ 3.62050113,  6.11939396,  3.10437388,  1.05255593,  8.19736308,
       -7.96333459, -6.77719773])

In [15]:
remainder, whole_part = np.modf(arr) #将array中值得整数和小数分离，作两个数组返回

In [16]:
remainder

array([ 0.62050113,  0.11939396,  0.10437388,  0.05255593,  0.19736308,
       -0.96333459, -0.77719773])

In [17]:
whole_part

array([ 3.,  6.,  3.,  1.,  8., -7., -6.])

In [24]:
arr

array([ 1.37940619,  1.57281305,  1.32737461,  1.0128877 ,  1.69207085,
               nan,         nan])

In [25]:
np.sqrt(arr)

array([ 1.17448124,  1.25411843,  1.15211744,  1.00642322,  1.30079624,
               nan,         nan])

In [26]:
arr

array([ 1.37940619,  1.57281305,  1.32737461,  1.0128877 ,  1.69207085,
               nan,         nan])

In [27]:
np.sqrt(arr, arr)

array([ 1.17448124,  1.25411843,  1.15211744,  1.00642322,  1.30079624,
               nan,         nan])

In [28]:
arr

array([ 1.17448124,  1.25411843,  1.15211744,  1.00642322,  1.30079624,
               nan,         nan])

End of 4.2 ,Ref:https://www.jianshu.com/p/a380222a3292