In [3]:
import tensorflow as tf
x = tf.constant([1.8, 2.2], dtype=tf.float32)
y = tf.cast(x, tf.int32)  # [1, 2], dtype=tf.int32

In [4]:
x

<tf.Tensor 'Const_1:0' shape=(2,) dtype=float32>

In [5]:
y

<tf.Tensor 'Cast_1:0' shape=(2,) dtype=int32>

In [6]:
with tf.Session() as sess:
    result = sess.run(x)
    print(result)

[ 1.79999995  2.20000005]


In [7]:
with tf.Session() as sess:
    result = sess.run(y)
    print(result)

[1 2]


In [9]:
z = tf.zeros([3, 4], tf.int32) 
with tf.Session() as sess:
    print(sess.run(z))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
