In [6]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [7]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [8]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  0.0000e+00  1.1098e-42
 0.0000e+00  7.0065e-45  0.0000e+00
-1.0122e+31  8.0154e-43  0.0000e+00
 0.0000e+00  7.0065e-45  0.0000e+00
-1.0151e+31  8.0154e-43  0.0000e+00
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix:



In [9]:
x = torch.rand(5, 3)
print(x)


 0.1308  0.8752  0.6349
 0.5037  0.6927  0.3667
 0.8495  0.6525  0.8246
 0.4356  0.3039  0.1411
 0.3250  0.4622  0.6505
[torch.FloatTensor of size 5x3]



Get its size:



In [10]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [11]:
y = torch.rand(5, 3)
print(x + y)


 0.2815  1.1807  1.0928
 0.9786  1.1430  0.8368
 0.9724  0.8648  1.5842
 1.1332  0.4156  0.4491
 1.0887  0.6972  1.1175
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [12]:
print(torch.add(x, y))


 0.2815  1.1807  1.0928
 0.9786  1.1430  0.8368
 0.9724  0.8648  1.5842
 1.1332  0.4156  0.4491
 1.0887  0.6972  1.1175
[torch.FloatTensor of size 5x3]



Addition: providing an output tensor as argument



In [13]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.2815  1.1807  1.0928
 0.9786  1.1430  0.8368
 0.9724  0.8648  1.5842
 1.1332  0.4156  0.4491
 1.0887  0.6972  1.1175
[torch.FloatTensor of size 5x3]



Addition: in-place



In [14]:
# adds x to y
y.add_(x)
print(y)


 0.2815  1.1807  1.0928
 0.9786  1.1430  0.8368
 0.9724  0.8648  1.5842
 1.1332  0.4156  0.4491
 1.0887  0.6972  1.1175
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [15]:
print(x[:, 1])


 0.8752
 0.6927
 0.6525
 0.3039
 0.4622
[torch.FloatTensor of size 5]



Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [17]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [18]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [19]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` method.



In [23]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

C:\Users\David\Anaconda3\envs\tensorflow\lib\site-packages\torch\tensor.py:293: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return self.add(other)


RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at d:\pytorch\pytorch\torch\lib\thc\generic/THCTensorMathPointwise.cu:301

### cuda 9.0以上不支持计算能为小于3的显卡,换cuda 8.0就可以了

安装CUDA 显卡GeForce 940MX （MI laptop）

CUDA（Compute Unified Device Architecture），是显卡厂商NVIDIA推出的运算平台。 

CUDA™是一种由NVIDIA推出的通用并行计算架构，该架构使GPU能够解决复杂的计算问题。 

它包含了CUDA指令集架构（ISA）以及GPU内部的并行计算引擎。 

开发人员现在可以使用C语言来为CUDA™架构编写程序，C语言是应用最广泛的一种高级编程语言。

所编写出的程序于是就可以在支持CUDA™的处理器上以超高性能运行。CUDA3.0已经开始支持C++和FORTRAN。

cuDNN的全称为NVIDIA CUDA® Deep Neural Network library，是NVIDIA专门针对深度神经网络（Deep Neural Networks）中的基础操作而设计基于GPU的加速库。cuDNN为深度神经网络中的标准流程提供了高度优化的实现方式，例如convolution、pooling、normalization以及activation layers的前向以及后向过程。

cuDNN只是NVIDIA深度神经网络软件开发包中的其中一种加速库。想了解NVIDIA深度神经网络加速库中的其他包请戳链接https://developer.nvidia.com/deep-learning-software。

各深度学习框架安装cuDNN需知
基本上所有的深度学习框架都支持cuDNN这一加速工具，例如：Caffe、Caffe2、TensorFlow、Torch、Pytorch、Theano等。

Caffe可以通过修改Makefile.config中的相应选项来修改是否在编译Caffe的过程中编译cuDNN，如果没有编译cuDNN的话，执行一些基于Caffe这一深度学习框架的程序速度上要慢3-5倍（Caffe官网上说不差多少，明明差很多嘛）。Caffe对cuDNN的版本不是很严格，只要大于cuDNN 4就可以。

TensorFlow目前的版本r1.2，强行要求装cuDNN，而且对版本也有相应的限制（cuDNN 5.1）。不过就官方说明看，TensorFlow将在下一个版本r1.3中加入对cuDNN 6.0的支持。

Torch通过LuaJit可以自动检测目前系统中的cuDNN版本来进行相应的编译（如没有cuDNN，也可在进行Torch的安装）。