In [1]:
import tensorflow as tf

In [2]:
tf.constant('Hello, TensorFlow!')  

<tf.Tensor 'Const:0' shape=() dtype=string>

In [3]:
# python 3.5.3
import tensorflow as tf
a = tf.constant([1.0, 2.0, 3.0], shape=[3], name='a')
b = tf.constant([1.0, 2.0, 3.0], shape=[3], name='b')
c = a + b
sess = tf.Session(config = tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

[ 2.  4.  6.]


In [6]:
import tensorflow as tf  

#两个矩阵相乘
x=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])  
y=tf.constant([[0,0,1.0],[0,0,1.0],[0,0,1.0]])
#注意这里这里x,y要有相同的数据类型，不然就会因为数据类型不匹配而出错
z=tf.multiply(x,y)

#两个数相乘
x1=tf.constant(1)
y1=tf.constant(2)
#注意这里这里x1,y1要有相同的数据类型，不然就会因为数据类型不匹配而出错
z1=tf.multiply(x1,y1)

#数和矩阵相乘
x2=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])
y2=tf.constant(2.0)
#注意这里这里x1,y1要有相同的数据类型，不然就会因为数据类型不匹配而出错
z2=tf.multiply(x2,y2)

with tf.Session() as sess:  
    print(sess.run(z))
    print(sess.run(z1))
    print(sess.run(z2))
    
z2=tf.multiply(x2,y2)  

[[ 0.  0.  3.]
 [ 0.  0.  3.]
 [ 0.  0.  3.]]
2
[[ 2.  4.  6.]
 [ 2.  4.  6.]
 [ 2.  4.  6.]]


In [5]:
import numpy as np
hello=tf.constant('hhh')
sess=tf.Session()
print (sess.run(hello))

b'hhh'


In [13]:
import tensorflow as tf
hello = tf.constant('hi,tensorflow')
sess = tf.Session()