In [1]:
import tensorflow as tf  

#两个矩阵相乘
x=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])  
y=tf.constant([[0,0,1.0],[0,0,1.0],[0,0,1.0]])
#注意这里这里x,y要有相同的数据类型，不然就会因为数据类型不匹配而出错
z=tf.multiply(x,y)

#两个数相乘
x1=tf.constant(1)
y1=tf.constant(2)
#注意这里这里x1,y1要有相同的数据类型，不然就会因为数据类型不匹配而出错
z1=tf.multiply(x1,y1)

#数和矩阵相乘
x2=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])
y2=tf.constant(2.0)
#注意这里这里x1,y1要有相同的数据类型，不然就会因为数据类型不匹配而出错
z2=tf.multiply(x2,y2)

with tf.Session() as sess:  
    print(sess.run(z))
    print(sess.run(z1))
    print(sess.run(z2))
    
z2=tf.multiply(x2,y2)  

[[ 0.  0.  3.]
 [ 0.  0.  3.]
 [ 0.  0.  3.]]
2
[[ 2.  4.  6.]
 [ 2.  4.  6.]
 [ 2.  4.  6.]]


In [2]:
with tf.device('/device:GPU:0'):
  a = tf.constant([1,2,3,4,5,6],shape=[2,3],name='a',dtype=tf.float32)
  b = tf.constant([1,2,3,4,5,6],shape=[3,2],name='b',dtype=tf.float32)
  c = tf.matmul(a,b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

[[ 22.  28.]
 [ 49.  64.]]


In [3]:
import tensorflow as tf
sess = tf.Session()
x1 = tf.constant(5)
x2 = tf.constant(6)

# runs result
print(sess.run(x1))

5


In [4]:
with tf.Session() as sess:
    matrix1 = tf.constant([[3., 3.]])
    print("matrix1:",matrix1)
    matrix2 = tf.constant([[2.],[2.]])
    print("matrix2:",matrix2)
    product = tf.matmul(matrix1, matrix2)

    with tf.device("/gpu:1"):
        result = sess.run(product)
        print("result:",result)

matrix1: Tensor("Const_8:0", shape=(1, 2), dtype=float32)
matrix2: Tensor("Const_9:0", shape=(2, 1), dtype=float32)
result: [[ 12.]]


In [5]:
import tensorflow as tf
a = tf.constant([1.,2.,3.,4.,5.,6.], shape=[2,3], name='a')
b = tf.constant([1.,2.,3.,4.,5.,6.], shape=[3,2], name='b')
c = tf.matmul(a,b)

with tf.Session(config= tf.ConfigProto(log_device_placement=True)) as sess:
    print(sess.run(c))

[[ 22.  28.]
 [ 49.  64.]]
